# -*- coding: utf-8 -*-
"""Proje.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pG0RRpZkJb0vwWAOBifcopqaVZg66Y8b
"""

#Kütüphane class
class Library:

    def __init__(self, file_name):  #txt dosyasını açmak için oluşturulan fonksiyon
        self.file_name = file_name
        self.file = open(self.file_name, "a+")
        self.file.seek(0)  # Dosyanın başına git
        self.books = self.file.read().splitlines()  # Satırları oku ve bir liste yap
        self.file.seek(0, 2)  # Dosyanın sonuna git

    def __del__(self):   #txt dosyasını kapatmak için oluşturulan fonksiyon
        self.file.close()

    def list_books(self):   #txt dosyasındaki kitap bilgilerini listelemek(output yazdırmak) için oluşturulan fonksiyon
        for book in self.books:
            title, author, year, pages = book.split(",")
            print(f"Book: {title}, Author: {author}, Year: {year}, Pages: {pages}")

    def add_book(self):    #txt dosyasındaki kitabı eklemek için oluşturulan fonksiyon
        title = input("Enter book title: ")
        author = input("Enter book author: ")
        year = input("Enter release year: ")
        pages = input("Enter number of pages: ")
        book_info = f"{title},{author},{year},{pages}"
        self.file.write(book_info + "\n")
        self.books.append(book_info)

    def remove_book(self):   #txt dosyasındaki kitabı silmek için oluşturulan fonksiyon
        title = input("Enter the title of the book you want to remove: ")
        new_books = []
        for book in self.books:
            if not book.startswith(title):
                new_books.append(book)
        self.file.seek(0)
        self.file.truncate()
        for book in new_books:
            self.file.write(book + "\n")
        self.books = new_books

# Kullanım
library = Library("Books.txt")
library.list_books()
library.add_book()
library.list_books()
library.remove_book()
library.list_books()

# Library sınıfından bir nesne oluşturalım
lib = Library("Books.txt")

# Menüyü ekrana yazdıralım
print("*** MENU ***")
print("1) List Books")
print("2) Add Book")
print("3) Remove Book")

# Kullanıcıdan menü seçeneğini alalım
menu_choice = input("Select an option (1-3): ")

# Seçime göre ilgili yöntemi çalıştıralım
if menu_choice == "1":
    lib.list_books()
elif menu_choice == "2":
    lib.add_book()
elif menu_choice == "3":
    lib.remove_book()
else:
    print("Invalid choice. Please select a valid option (1-3).")